title: Connell McCarthy
email: me@connellmccarthy.com
description: >- # this means to ignore newlines until "baseurl:"
  A multi-faceted Canadian Creative with a passion for 
  finding the blend between aesthetic and functionality.
url: "https://connellmccarthy.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: connellmccarthy
github_username:  connellmccarthy
permalink: pretty
image_path: /assets/articles/

sass:
  sass_dir: _sass
  style: compressed
collections:
  articles:
    output: true
    sort_by: date
    permalink: "/:collection/:path/"
    future: false
  collection:
    output: true
    sort_by: title
    permalink: "/:collection/:path"
  products:
    output: true
    sort_by: title
    permalink: "/:collection/:path"
